# Generated by Django 3.1.2 on 2020-10-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0006_auto_20201022_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProduct',
            new_name='ExCartProduct',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='ExOrder',
        ),
    ]
