# Generated by Django 3.1.2 on 2020-10-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201022_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excustomer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='excustomer',
            name='phone',
        ),
    ]
