# Generated by Django 3.1.2 on 2020-10-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201022_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excart',
            name='product_price',
        ),
        migrations.AddField(
            model_name='excartproduct',
            name='product_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='excartproduct',
            name='final_price',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField(default=0, verbose_name='Цена продукта'), verbose_name='Общая цена'),
        ),
    ]
