# Generated by Django 3.1.2 on 2020-10-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201023_0821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExCart',
            new_name='Cart',
        ),
        migrations.AlterModelOptions(
            name='excartproduct',
            options={'verbose_name': 'Продукт в корзине', 'verbose_name_plural': 'Продукты в корзине'},
        ),
        migrations.AlterField(
            model_name='excartproduct',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая цена'),
        ),
    ]
