# Generated by Django 3.1.2 on 2020-10-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0010_auto_20201023_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExCartProduct',
            new_name='ECartProduct',
        ),
    ]
