# Generated by Django 3.1.2 on 2020-10-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0011_auto_20201023_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ECartProduct',
            new_name='CartProduct',
        ),
    ]
