# Generated by Django 3.1.2 on 2020-10-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201023_1046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExCustomer',
            new_name='Customer',
        ),
    ]
