# Generated by Django 3.1.2 on 2020-10-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201023_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='exorder',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер заказа'),
        ),
    ]
