# Generated by Django 3.1.2 on 2020-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_exorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_products',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
