# Generated by Django 3.1.2 on 2020-10-27 06:10

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cart_total_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exorder',
            name='number',
            field=models.PositiveIntegerField(default=builtins.id, verbose_name='Номер заказа'),
        ),
    ]
