# Generated by Django 3.1.2 on 2020-10-27 06:13

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201027_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exorder',
            name='number',
            field=models.CharField(default=builtins.id, max_length=10, verbose_name='Номер заказа'),
        ),
    ]
