# Generated by Django 3.1.2 on 2020-10-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20201027_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exorder',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Номер заказа'),
        ),
    ]
