# Generated by Django 3.1.2 on 2020-10-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_exorder_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exorder',
            name='products',
        ),
    ]
