# Generated by Django 3.1.2 on 2020-11-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_review_product_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_comment',
            new_name='comment_for_product',
        ),
    ]
