# Generated by Django 3.1.2 on 2020-11-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20201110_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exorder',
            name='address',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Адрес'),
        ),
    ]
