# Generated by Django 3.1.2 on 2020-11-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20201113_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='iron',
            name='category',
            field=models.CharField(default='iron', max_length=250, verbose_name='имя модели'),
        ),
    ]
