# Generated by Django 3.1.2 on 2020-11-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_iron_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExOrder',
            new_name='Order',
        ),
    ]
