# Generated by Django 3.1.2 on 2020-11-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20201114_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во отзывов'),
        ),
    ]
