# Generated by Django 3.1.2 on 2020-11-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_review_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment_for_product',
            field=models.TextField(null=True, verbose_name='комментарий для продукта'),
        ),
    ]
