# Generated by Django 3.1.2 on 2020-11-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20201119_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drymachine',
            name='image',
            field=models.ImageField(upload_to='D:\\python\\dj\\mysite\\media\\drymachine.png', verbose_name='Изображение'),
        ),
    ]
