# Generated by Django 3.1.2 on 2020-11-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20201119_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drymachine',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
    ]
