# Generated by Django 3.1.2 on 2020-11-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20201119_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drymachine',
            name='d_hatch',
        ),
        migrations.RemoveField(
            model_name='drymachine',
            name='diagnostics_fault',
        ),
        migrations.RemoveField(
            model_name='drymachine',
            name='illumination',
        ),
        migrations.RemoveField(
            model_name='drymachine',
            name='lines_true',
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='width',
            field=models.FloatField(default=25.6, verbose_name='Ширина'),
        ),
    ]
