# Generated by Django 3.1.2 on 2020-11-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20201119_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drymachine',
            name='width',
            field=models.DecimalField(decimal_places=2, default=25.6, max_digits=10, verbose_name='Ширина'),
        ),
    ]
