# Generated by Django 3.1.2 on 2020-11-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20201119_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='drymachine',
            name='country',
            field=models.CharField(db_index=True, default='Турция', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='No_child',
            field=models.CharField(default='есть', max_length=100, verbose_name='Блокировка от детей'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='class_energy',
            field=models.CharField(db_index=True, default='В', max_length=150, verbose_name='Класс энергопотребления'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='color',
            field=models.CharField(default='белый', max_length=100, verbose_name='Основной цвет'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='control',
            field=models.CharField(default='кнопки', max_length=100, verbose_name='Вид управления'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='cotton',
            field=models.CharField(default='есть', max_length=100, verbose_name='Хлопок'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='display',
            field=models.CharField(db_index=True, default='есть', max_length=50, verbose_name='Дисплей'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='dry_type',
            field=models.CharField(db_index=True, default='конденсационная', max_length=100, verbose_name='Тип сушки'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='fault',
            field=models.CharField(default='нет', max_length=100, verbose_name='Индикация неисправностей'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='heat_pump',
            field=models.CharField(default='нет', max_length=100, verbose_name='Тепловой насос'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='humidity_linen',
            field=models.CharField(default='есть', max_length=100, verbose_name='Определение влажности белья'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='overheating',
            field=models.CharField(default='нет', max_length=100, verbose_name='Защита от перегрева'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='postponing_start',
            field=models.CharField(default='есть', max_length=100, verbose_name='Отсрочка старта'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='sensitive_lines',
            field=models.CharField(default='нет', max_length=100, verbose_name='Чувствительное бельё'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='synthetics',
            field=models.CharField(default='есть', max_length=100, verbose_name='Синтетика'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='type',
            field=models.CharField(db_index=True, default='сушильная машина', max_length=150, verbose_name='Тип изделия'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='width',
            field=models.DecimalField(decimal_places=1, default=25.6, max_digits=10, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='wool',
            field=models.CharField(default='нет', max_length=100, verbose_name='Шерсть'),
        ),
    ]
