# Generated by Django 3.1.2 on 2020-11-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_washmachine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drymachine',
            name='review',
            field=models.IntegerField(default=1, verbose_name='Кол-во отзывов'),
        ),
    ]
