# Generated by Django 3.1.2 on 2020-11-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_auto_20201119_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drymachine',
            options={'verbose_name': 'Сушильные машины', 'verbose_name_plural': 'Сушильные машины'},
        ),
        migrations.RemoveField(
            model_name='washmachine',
            name='activator',
        ),
        migrations.RemoveField(
            model_name='washmachine',
            name='add_color',
        ),
        migrations.RemoveField(
            model_name='washmachine',
            name='autobalance',
        ),
        migrations.RemoveField(
            model_name='washmachine',
            name='choice_speed',
        ),
        migrations.RemoveField(
            model_name='washmachine',
            name='functional',
        ),
        migrations.RemoveField(
            model_name='washmachine',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='washmachine',
            name='postponement',
        ),
        migrations.RemoveField(
            model_name='washmachine',
            name='temperature',
        ),
        migrations.AddField(
            model_name='submenu',
            name='mode',
            field=models.CharField(blank=True, default='none', max_length=300, null=True, verbose_name='Имя модели'),
        ),
        migrations.AddField(
            model_name='washmachine',
            name='country',
            field=models.CharField(db_index=True, default=12, max_length=100, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='washmachine',
            name='postponing_start',
            field=models.CharField(default='есть', max_length=100, verbose_name='Отсрочка запуска'),
        ),
        migrations.AddField(
            model_name='washmachine',
            name='review',
            field=models.IntegerField(default=0, verbose_name='Кол-во отзывов'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='review',
            field=models.IntegerField(default=0, verbose_name='Кол-во отзывов'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='No_child',
            field=models.CharField(default='есть', max_length=100, verbose_name='Блокировка от детей'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='box_water',
            field=models.CharField(default='есть', max_length=100, verbose_name='Бак для воды'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='class_wash',
            field=models.CharField(default='А', max_length=100, verbose_name='Класс стирки'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='color',
            field=models.CharField(default='белый', max_length=100, verbose_name='Основной цвет'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='control',
            field=models.CharField(default='кнопки', max_length=100, verbose_name='Тип управления'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='display',
            field=models.CharField(db_index=True, default='есть', max_length=50, verbose_name='Дисплей'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='drive',
            field=models.CharField(db_index=True, default='нет', max_length=100, verbose_name='Прямой привод'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='leak',
            field=models.CharField(default='есть', max_length=100, verbose_name='Защита от протечек'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='motor',
            field=models.CharField(default='есть', max_length=100, verbose_name='Инверторный двигатель'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='shop',
            field=models.CharField(db_index=True, default='есть', max_length=150, verbose_name='Наличие в магазине'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='steam',
            field=models.CharField(default='есть', max_length=100, verbose_name='Обработка паром'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='type',
            field=models.CharField(db_index=True, default='стиральная машина', max_length=150, verbose_name='Тип изделия'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='upload_type',
            field=models.CharField(db_index=True, default='фронтальная', max_length=100, verbose_name='Тип загрузки'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='view',
            field=models.CharField(db_index=True, default='автомат', max_length=100, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='voice',
            field=models.CharField(default='есть', max_length=100, verbose_name='Звуковой сигнал окончания стирки'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='voltage',
            field=models.CharField(default='есть', max_length=100, verbose_name='Защита от скачков напряжения'),
        ),
    ]
