# Generated by Django 3.1.2 on 2020-11-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_auto_20201120_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submenu',
            old_name='mode',
            new_name='model',
        ),
    ]
