# Generated by Django 3.1.2 on 2020-11-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_auto_20201124_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drymachine',
            name='block_child',
            field=models.CharField(blank=True, choices=[('True', 'есть'), ('Fasle', 'нет')], default='True', max_length=100, null=True, verbose_name='Блокировка от детей'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='heat_pump',
            field=models.CharField(blank=True, choices=[('True', 'есть'), ('Fasle', 'нет')], default='Fasle', max_length=100, null=True, verbose_name='Тепловой насос'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='max_load',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Мак загрузка'),
        ),
    ]
