# Generated by Django 3.1.2 on 2020-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_auto_20201124_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drymachine',
            name='max_load',
            field=models.FloatField(default=3, verbose_name='Мах загрузка'),
        ),
    ]
