# Generated by Django 3.1.2 on 2020-11-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_auto_20201125_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drymachine',
            old_name='manufacturer',
            new_name='manufacture',
        ),
        migrations.RenameField(
            model_name='washmachine',
            old_name='manufacturer',
            new_name='manufacture',
        ),
    ]
