# Generated by Django 3.1.2 on 2020-11-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_auto_20201125_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washmachine',
            name='box_water',
        ),
    ]
