# Generated by Django 3.1.2 on 2020-11-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_remove_washmachine_box_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='iron',
            name='manufacture',
            field=models.CharField(db_index=True, default='Италия', max_length=100, verbose_name='Производитель'),
        ),
    ]
