# Generated by Django 3.1.2 on 2020-11-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_auto_20201127_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products_for_order',
            field=models.TextField(blank=True, null=True, verbose_name='Продукт(ы) в корзине'),
        ),
    ]
