# Generated by Django 3.1.2 on 2020-11-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_remove_order_products_for_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_for_order',
            field=models.TextField(default=None, verbose_name='Продукт(ы) в корзине'),
        ),
    ]
