# Generated by Django 3.1.2 on 2020-11-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_auto_20201127_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
