# Generated by Django 3.1.2 on 2020-11-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_remove_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='for_anon_user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='in_order',
        ),
    ]
