# Generated by Django 3.1.2 on 2020-11-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_auto_20201127_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drymachine',
            old_name='valume',
            new_name='volume',
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во продуктов'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='model',
            field=models.CharField(blank=True, default='none', max_length=300, null=True, verbose_name='Имя модели продукта'),
        ),
    ]
