# Generated by Django 3.1.2 on 2020-11-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_auto_20201130_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drymachine',
            name='load_postponing',
            field=models.CharField(default=1, max_length=100, verbose_name='Продолжительность отсрочки'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='program',
            field=models.CharField(default=1, max_length=100, verbose_name='Общее кол-во программ'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='value_noice',
            field=models.CharField(default=1, max_length=100, verbose_name='Уровень шума'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='valume',
            field=models.CharField(default=1, max_length=100, verbose_name='Объём барабана'),
        ),
    ]
