# Generated by Django 3.1.2 on 2020-11-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_auto_20201130_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drymachine',
            name='depth',
            field=models.CharField(default=1, max_length=100, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='height',
            field=models.CharField(max_length=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='massa',
            field=models.CharField(max_length=100, verbose_name='Вес'),
        ),
    ]
