# Generated by Django 3.1.2 on 2020-11-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_auto_20201130_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drymachine',
            name='block_child',
            field=models.CharField(default='есть', max_length=100, verbose_name='Блокировка от детей'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='cotton',
            field=models.CharField(default='есть', max_length=100, verbose_name='Хлопок'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='fault',
            field=models.CharField(default='есть', max_length=100, verbose_name='Индикация неисправностей'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='height',
            field=models.CharField(default=1, max_length=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='humidity_linen',
            field=models.CharField(default='есть', max_length=100, verbose_name='Определение влажности белья'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='massa',
            field=models.CharField(default=1, max_length=100, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='overheating',
            field=models.CharField(default='есть', max_length=100, verbose_name='Защита от перегрева'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='postponing_start',
            field=models.CharField(default='есть', max_length=100, verbose_name='Отсрочка старта'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='sensitive_lines',
            field=models.CharField(default='есть', max_length=100, verbose_name='Чувствительное бельё'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='shop',
            field=models.CharField(default='есть', max_length=150, verbose_name='Наличие в магазине'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='synthetics',
            field=models.CharField(default='есть', max_length=100, verbose_name='Синтетика'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='wool',
            field=models.CharField(default='есть', max_length=100, verbose_name='Шерсть'),
        ),
    ]
