# Generated by Django 3.1.2 on 2020-11-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_auto_20201130_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drymachine',
            name='max_load',
            field=models.CharField(default=3, max_length=100, verbose_name='Мах загрузка'),
        ),
    ]
