# Generated by Django 3.1.2 on 2020-11-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0079_auto_20201130_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drymachine',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='drymachine',
            name='height',
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='width',
            field=models.CharField(default=1, max_length=100, verbose_name='Глубина'),
        ),
    ]
