# Generated by Django 3.1.2 on 2020-11-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0080_auto_20201130_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='drymachine',
            name='depth',
            field=models.CharField(default=1, max_length=100, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='drymachine',
            name='height',
            field=models.CharField(default=1, max_length=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='width',
            field=models.CharField(default=25.6, max_length=100, verbose_name='Ширина'),
        ),
    ]
