# Generated by Django 3.1.2 on 2020-12-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0082_auto_20201130_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='iron',
            name='country',
            field=models.CharField(default='Италия', max_length=200, verbose_name='Страна производитель'),
        ),
        migrations.AddField(
            model_name='iron',
            name='depth',
            field=models.CharField(default='bosch', max_length=100, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='iron',
            name='height',
            field=models.CharField(default='bosch', max_length=100, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='iron',
            name='massa',
            field=models.CharField(default='bosch', max_length=100, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='iron',
            name='security',
            field=models.CharField(default='1 мес.', max_length=8, verbose_name='Гарантия'),
        ),
        migrations.AddField(
            model_name='iron',
            name='width',
            field=models.CharField(default='bosch', max_length=100, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='drymachine',
            name='value_noice',
            field=models.CharField(default='65 дБ', max_length=100, verbose_name='Уровень шума'),
        ),
        migrations.AlterField(
            model_name='iron',
            name='manufacture',
            field=models.CharField(default='bosch', max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='iron',
            name='type',
            field=models.CharField(default='iron', max_length=150, verbose_name='Тип изделия'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='display',
            field=models.CharField(default='есть', max_length=50, verbose_name='Дисплей'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='drive',
            field=models.CharField(default='нет', max_length=100, verbose_name='Прямой привод'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='manufacture',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='security',
            field=models.CharField(max_length=100, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='shop',
            field=models.CharField(default='есть', max_length=150, verbose_name='Наличие в магазине'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='type',
            field=models.CharField(default='стиральная машина', max_length=150, verbose_name='Тип изделия'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='upload_type',
            field=models.CharField(default='фронтальная', max_length=100, verbose_name='Тип загрузки'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='view',
            field=models.CharField(default='автомат', max_length=100, verbose_name='Вид'),
        ),
    ]
