# Generated by Django 3.1.2 on 2020-12-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0084_auto_20201201_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='fridge', max_length=250, verbose_name='имя модели')),
                ('url', models.SlugField(max_length=200, unique=True, verbose_name='url')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('security', models.CharField(max_length=5, verbose_name='Гарантия')),
                ('manufacture', models.CharField(max_length=200, verbose_name='Страна производитель')),
                ('type', models.CharField(db_index=True, default='Холодильник', max_length=150, verbose_name='Тип изделия')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(default='white', max_length=100, verbose_name='Основной цвет')),
                ('design_type', models.CharField(default='полноразмерный с морозильником', max_length=100, verbose_name='Тип конструкции')),
                ('total_useful_volume', models.CharField(default='80 л', max_length=100, verbose_name='Общий полезный объём')),
                ('volume_refrigerator_compartment', models.CharField(default='80 л', max_length=100, verbose_name='Полезный объём холодильной камеры')),
                ('volume_refrigerator_compartment_NTO', models.CharField(default=' 80 л', max_length=100, verbose_name='Полезный объём холодильной камеры/НТО')),
                ('location_freezer_NTO', models.CharField(default='сверху', max_length=100, verbose_name='Расположение морозильной камеры/НТО')),
                ('material_outer_covering', models.CharField(default='металл', max_length=100, verbose_name='Материал внешнего покрытия')),
                ('shelf_material', models.CharField(default='металл', max_length=100, verbose_name='Материал полок')),
                ('door_opening', models.CharField(default='направо', max_length=100, verbose_name='Открытие дверей')),
                ('energy_consumption', models.CharField(max_length=100, verbose_name='Энергопотребление')),
                ('freezing_power', models.CharField(max_length=100, verbose_name='Мощность замораживания')),
                ('cold_storage_system', models.CharField(max_length=100, verbose_name='Система холодильного отделения')),
                ('min_temperature_freezer_NTO', models.CharField(max_length=100, verbose_name='Мин. температура морозильной камеры/НТО')),
                ('value_noize', models.CharField(max_length=100, verbose_name='Уровень шума')),
                ('width', models.CharField(default='50 см', max_length=100, verbose_name='Ширина')),
                ('height', models.CharField(default='50 см', max_length=100, verbose_name='Высота')),
                ('depth', models.CharField(default='51 см', max_length=100, verbose_name='Глубина')),
                ('massa', models.CharField(default='25 кг', max_length=100, verbose_name='Вес')),
            ],
        ),
    ]
