# Generated by Django 3.1.2 on 2020-12-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0085_fridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='stove', max_length=250, verbose_name='имя модели')),
                ('url', models.SlugField(max_length=200, unique=True, verbose_name='url')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('security', models.CharField(default='12 мес.', max_length=5, verbose_name='Гарантия')),
                ('manufacture', models.CharField(max_length=200, verbose_name='Страна производитель')),
                ('type', models.CharField(default='Плитка электрическая', max_length=150, verbose_name='Тип изделия')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(default='белый', max_length=100, verbose_name='Основной цвет')),
                ('total_number_burnets', models.CharField(default='2 шт', max_length=10, verbose_name='Общие кол-во комфорок')),
                ('volume_oven', models.CharField(default='24 л', max_length=10, verbose_name='Объём духовки')),
                ('max_power_consumption', models.CharField(default='3 кВт', max_length=5, verbose_name='Мак потребляемая мощность')),
                ('supply_voltage', models.CharField(default='220 В', max_length=100, verbose_name='Напряжение питания')),
                ('energy_consumption_class', models.CharField(default='А', max_length=100, verbose_name='Класс энергопотребления')),
                ('type_management', models.CharField(default='поворотный механизм', max_length=100, verbose_name='Вид управления')),
                ('display', models.CharField(default='нет', max_length=100, verbose_name='Дисплей')),
                ('housing_material_coating', models.CharField(default='эмаль', max_length=100, verbose_name='Материал/покрытие корпуса')),
                ('timer', models.CharField(default='нет', max_length=100, verbose_name='Таймер')),
                ('grill', models.CharField(default='нет', max_length=100, verbose_name='Гриль')),
                ('max_temperature', models.CharField(default='300°', max_length=100, verbose_name='Мах температура')),
                ('oven_light', models.CharField(default='нет', max_length=100, verbose_name='Подсветка духовки')),
                ('material_cover_panel', models.CharField(default='эмалированная сталь', max_length=100, verbose_name='Материал покрытия панели')),
                ('induction_burners', models.CharField(default='нет', max_length=100, verbose_name='Индукционные конфорки')),
                ('number_double_circuit_burners', models.CharField(default='нет', max_length=100, verbose_name='Число двухконтурных конфорок')),
                ('number_three_circuit_burners', models.CharField(default='нет', max_length=100, verbose_name='Число трехконтурных конфорок')),
                ('width', models.CharField(default='50 см', max_length=100, verbose_name='Ширина')),
                ('height', models.CharField(default='50 см', max_length=100, verbose_name='Высота')),
                ('depth', models.CharField(default='50 см', max_length=100, verbose_name='Глубина')),
                ('massa', models.CharField(default='50 кг', max_length=100, verbose_name='Вес')),
            ],
        ),
    ]
