# Generated by Django 3.1.2 on 2020-12-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0086_stove'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrowaveOven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='microwaveoven', max_length=250, verbose_name='имя модели')),
                ('url', models.SlugField(max_length=200, unique=True, verbose_name='url')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('security', models.CharField(default='12 мес.', max_length=5, verbose_name='Гарантия')),
                ('manufacture', models.CharField(max_length=200, verbose_name='Страна производитель')),
                ('type', models.CharField(default='Микроволновая печь', max_length=150, verbose_name='Тип изделия')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(default='белый', max_length=100, verbose_name='Основной цвет')),
                ('power_microwaves', models.CharField(default='700 Вт', max_length=100, verbose_name='Мощность микроволн')),
                ('energy_consumption', models.CharField(default='1150 Вт', max_length=100, verbose_name='Энергопотребление')),
                ('internal_volume', models.CharField(default='20 л', max_length=100, verbose_name='Внутренний объём')),
                ('rotary_table', models.CharField(default='есть', max_length=100, verbose_name='Поворотный стол')),
                ('diameter_pan', models.CharField(default='24 см', max_length=100, verbose_name='Диаметр поддона')),
                ('inner_coating_camera', models.CharField(default='эмалированная сталь', max_length=100, verbose_name='Внутреннее покрытие камеры')),
                ('type_management', models.CharField(default='поворотный механизм', max_length=100, verbose_name='Вид управления')),
                ('block_child', models.CharField(default='нет', max_length=100, verbose_name='Блокировка от детей')),
                ('display', models.CharField(default='есть', max_length=100, verbose_name='Дисплей')),
                ('timer', models.CharField(default='есть', max_length=100, verbose_name='Таймер')),
                ('programs', models.CharField(default='нет', max_length=100, verbose_name='Автоматические программы приготовления')),
                ('beep', models.CharField(default='нет', max_length=100, verbose_name='Отключение звукового сигнала')),
                ('start', models.CharField(default='нет', max_length=100, verbose_name='Отсрочка старта')),
                ('width', models.CharField(default='45 см', max_length=100, verbose_name='Ширина')),
                ('height', models.CharField(default='25 см', max_length=100, verbose_name='Высота')),
                ('depth', models.CharField(default='25 см', max_length=100, verbose_name='Глубина')),
                ('massa', models.CharField(default='10 кг', max_length=100, verbose_name='Вес')),
            ],
        ),
    ]
