# Generated by Django 3.1.2 on 2020-12-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0087_microwaveoven'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kettle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='kettle', max_length=250, verbose_name='имя модели')),
                ('url', models.SlugField(max_length=200, unique=True, verbose_name='url')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('security', models.CharField(default='12 мес.', max_length=5, verbose_name='Гарантия')),
                ('manufacture', models.CharField(max_length=200, verbose_name='Страна производитель')),
                ('type', models.CharField(default='Электрочайник', max_length=150, verbose_name='Тип изделия')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(default='белый', max_length=100, verbose_name='Основной цвет')),
                ('volume', models.CharField(default='1 л', max_length=100, verbose_name='Объём')),
                ('power', models.CharField(default='800 Вт', max_length=100, verbose_name='Мощность')),
                ('body_material', models.CharField(default='пластик', max_length=100, verbose_name='Материал корпуса')),
                ('voltage', models.CharField(default='220 Вт', max_length=100, verbose_name='Напряжение питания')),
                ('temperature', models.CharField(default='100°', max_length=100, verbose_name='Температура нагрева воды')),
                ('light', models.CharField(default='нет', max_length=100, verbose_name='Подсветка')),
                ('cord_length', models.CharField(default='0.8 м', max_length=100, verbose_name='Длина сетевого шнура')),
                ('autopower', models.CharField(default='есть', max_length=100, verbose_name='Автоотключение')),
                ('cover', models.CharField(default='откидная защёлкивающая крышка', max_length=100, verbose_name='Особенности крышки')),
                ('width', models.CharField(default='40 см', max_length=100, verbose_name='Ширина')),
                ('height', models.CharField(default='30 см', max_length=100, verbose_name='Высота')),
                ('depth', models.CharField(default='20 см', max_length=100, verbose_name='Глубина')),
                ('massa', models.CharField(default='2 кг', max_length=100, verbose_name='Вес')),
            ],
        ),
    ]
