# Generated by Django 3.1.2 on 2020-12-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0089_auto_20201201_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='smartphone', max_length=250, verbose_name='имя модели')),
                ('url', models.SlugField(max_length=200, unique=True, verbose_name='url')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('security', models.CharField(default='12 мес.', max_length=5, verbose_name='Гарантия')),
                ('manufacture', models.CharField(max_length=200, verbose_name='Страна производитель')),
                ('type', models.CharField(default='Смартфон', max_length=150, verbose_name='Тип изделия')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(default='чёрный', max_length=100, verbose_name='Основной цвет')),
                ('add_color', models.CharField(default='white', max_length=100, verbose_name='Дополнительный цвет')),
                ('year', models.CharField(max_length=100, verbose_name='Год выпуска')),
                ('net_2G', models.CharField(default='GSM 850, GSM 1900, GSM 1800, GSM 900', max_length=100, verbose_name='Поддержка сетей 2G')),
                ('net_3G', models.CharField(default='UMTS 850, UMTS 2100, UMTS 900', max_length=100, verbose_name='Поддержка сетей 3G')),
                ('net_4G', models.CharField(default='есть', max_length=100, verbose_name='Поддержка сетей 4G(LTE)')),
                ('volume_LTE', models.CharField(default='(B38), LTE 1800 (B3), LTE 900 (B8), LTE 800 (B20), LTE 2300 (B40), LTE 2600 (B7)', max_length=100, verbose_name='Диапозон частот LTE')),
                ('format_SIM', models.CharField(default='Nano-SIM', max_length=100, verbose_name='Формат SIM-карт')),
                ('number_SIM', models.CharField(default='2', max_length=100, verbose_name='Количество SIM-карт')),
                ('screen_diagonal', models.CharField(default='5.3"', max_length=100, verbose_name='Диагональ экрана')),
                ('screen_resolution', models.CharField(default='1480x720', max_length=100, verbose_name='Разрешение экрана')),
                ('screen_technology', models.CharField(default='TN', max_length=100, verbose_name='Технология изготовления экрана')),
                ('aspect_ratio', models.CharField(default='18:9', max_length=100, verbose_name='Соотношение сторон')),
                ('OS', models.CharField(default='Android 10', max_length=100, verbose_name='Версия ОС')),
                ('model_processor', models.CharField(default='MediaTek', max_length=100, verbose_name='Модель процессора')),
                ('number_cores', models.CharField(default='4', max_length=100, verbose_name='Кол-во ядер')),
                ('amount_RAM', models.CharField(default='1 Гб', max_length=100, verbose_name='Объём оперативной памяти')),
                ('amount_internal_memory', models.CharField(default='16 Гб', max_length=100, verbose_name='Объём встроенной памяти')),
                ('type_maps', models.CharField(default='microSD', max_length=100, verbose_name='Типы поддерживаемых карт')),
                ('max_memory_card_size', models.CharField(default='512 Гб', max_length=100, verbose_name='Мак объём карты памяти')),
                ('number_camera', models.CharField(default='1', max_length=100, verbose_name='Кол-во основных(тыловых) камер')),
                ('number_megapixels', models.CharField(default='8 Мп', max_length=100, verbose_name='Кол-во мегапикселей основной камеры')),
                ('resolution_picture', models.CharField(default='1480x720', max_length=100, verbose_name='Разрешение снимков')),
                ('format_video', models.CharField(default='Full HD', max_length=100, verbose_name='Формат видеосъёмки')),
                ('slow_video', models.CharField(default='нет', max_length=100, verbose_name='Замедленная видеосъемка')),
                ('battery_capacity', models.CharField(default='3000 мА*ч', max_length=100, verbose_name='Ёмкость аккумулятора')),
                ('time_battery', models.CharField(default='17 ч', max_length=100, verbose_name='Время работы в режиме разговора')),
                ('width', models.CharField(default='125 мм', max_length=100, verbose_name='Ширина')),
                ('height', models.CharField(default='125 мм', max_length=100, verbose_name='Высота')),
                ('depth', models.CharField(default='125 мм', max_length=100, verbose_name='Глубина')),
                ('massa', models.CharField(default='150 г', max_length=100, verbose_name='Вес')),
            ],
        ),
    ]
