# Generated by Django 3.1.2 on 2020-12-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0090_smartphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartWatche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='smartwatche', max_length=250, verbose_name='имя модели')),
                ('url', models.SlugField(max_length=200, unique=True, verbose_name='url')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('security', models.CharField(default='12 мес.', max_length=5, verbose_name='Гарантия')),
                ('manufacture', models.CharField(max_length=200, verbose_name='Страна производитель')),
                ('type', models.CharField(default='Смартчасы', max_length=150, verbose_name='Тип изделия')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('body_color', models.CharField(default='чёрный', max_length=100, verbose_name='Цвет корпуса')),
                ('strap_color', models.CharField(default='чёрный', max_length=100, verbose_name='Цвет ремешка')),
                ('type_control', models.CharField(default='сенсорное', max_length=100, verbose_name='Тип управления')),
                ('compatible_devices', models.CharField(default='iOS устройства, Android устройства', max_length=100, verbose_name='Совместимость с устройствами')),
                ('display_availability', models.CharField(default='есть', max_length=100, verbose_name='Наличие дисплея')),
                ('dial_type', models.CharField(default='ЖК-дисплей', max_length=100, verbose_name='Тип циферблата')),
                ('sensor_display', models.CharField(default='нет', max_length=100, verbose_name='Сенсорный дисплей')),
                ('diagonal', models.CharField(default='1.3"', max_length=100, verbose_name='Диагональ')),
                ('display_form_factor', models.CharField(default='квадратный', max_length=100, verbose_name='Форм-фактор дисплея')),
                ('degree_protection', models.CharField(default='IP67', max_length=100, verbose_name='Степень защиты')),
                ('band_material', models.CharField(default='гипоаллергенный силикон', max_length=100, verbose_name='Материал ремешка')),
                ('size_strap', models.CharField(default='регулируемый', max_length=100, verbose_name='Размер ремешка')),
                ('wireless_communication', models.CharField(default='Bluetooth', max_length=100, verbose_name='Беспроводная связь')),
                ('bluetooth_version', models.CharField(default='4', max_length=100, verbose_name='Версия Bluetooth')),
                ('gps', models.CharField(default='нет', max_length=100, verbose_name='GPS')),
                ('sim_cart', models.CharField(default='нет', max_length=100, verbose_name='Слот для SIM-карты')),
                ('type_food', models.CharField(default='аккумулятор', max_length=100, verbose_name='Тип питания')),
                ('battery_capacity', models.CharField(default='150 мА*ч', max_length=100, verbose_name='Ёмкость аккумулятора')),
                ('time_job', models.CharField(default='336 ч', max_length=100, verbose_name='Время работы')),
                ('width', models.CharField(default='125 мм', max_length=100, verbose_name='Ширина')),
                ('height', models.CharField(default='125 мм', max_length=100, verbose_name='Высота')),
                ('depth', models.CharField(default='125 мм', max_length=100, verbose_name='Глубина')),
                ('massa', models.CharField(default='33 г', max_length=100, verbose_name='Вес')),
            ],
        ),
    ]
