# Generated by Django 3.1.2 on 2020-12-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0091_smartwatche'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmartWatche',
            new_name='SmartWatch',
        ),
    ]
