# Generated by Django 3.1.2 on 2020-12-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0094_auto_20201202_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='cold_storage_system',
            field=models.CharField(default='капельная', max_length=100, verbose_name='Система холодильного отделения'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='color',
            field=models.CharField(default='серый', max_length=100, verbose_name='Основной цвет'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='energy_consumption',
            field=models.CharField(default='284 кВт/год', max_length=100, verbose_name='Энергопотребление'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='freezing_power',
            field=models.CharField(default='4 кг/сутки', max_length=100, verbose_name='Мощность замораживания'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='min_temperature_freezer_NTO',
            field=models.CharField(default='-24°', max_length=100, verbose_name='Мин. температура морозильной камеры/НТО'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='security',
            field=models.CharField(default='24 мес.', max_length=10, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='value_noize',
            field=models.CharField(default='40 дБ', max_length=100, verbose_name='Уровень шума'),
        ),
    ]
