# Generated by Django 3.1.2 on 2020-12-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0097_auto_20201202_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairclipper',
            name='width_knife',
        ),
        migrations.AlterField(
            model_name='hairclipper',
            name='professional',
            field=models.CharField(default='нет', max_length=100, verbose_name='Профессиональная техника'),
        ),
    ]
