# Generated by Django 3.1.2 on 2020-12-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0098_auto_20201202_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brackettv',
            name='manufacture',
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='adjustment',
            field=models.CharField(default='фиксированный', max_length=100, verbose_name='Способ регулировки'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='angle_rotation',
            field=models.CharField(default='нет', max_length=100, verbose_name='Угол поворота ответной части'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='attachment_point',
            field=models.CharField(default='к стене', max_length=100, verbose_name='Место крепления кронштейна'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='max_diagonal_screen',
            field=models.CharField(default='10"', max_length=100, verbose_name='Мин диагональ экрана'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='max_distance',
            field=models.CharField(default='21 мм', max_length=100, verbose_name='Мах расстояние от стены/потолка'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='max_load',
            field=models.CharField(default='25 кг', max_length=100, verbose_name='Мах нагрузка'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='min_diagonal_screen',
            field=models.CharField(default='26"', max_length=100, verbose_name='Мах диагональ экрана'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='min_distance',
            field=models.CharField(default='21 мм', max_length=100, verbose_name='Мин расстояние от стены/потолка'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='standard_mounting_dimension',
            field=models.CharField(default='100 x 100, 75 x 75', max_length=100, verbose_name='Стандарт размеров крипления'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='tilt_angle_down',
            field=models.CharField(default='нет', max_length=100, verbose_name='Угол наклона вниз'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='tilt_angle_up',
            field=models.CharField(default='нет', max_length=100, verbose_name='Угол наклона вверх'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='type_TV',
            field=models.CharField(default='кронштейн для ТВ', max_length=100, verbose_name='Тип кронштейна'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='HDTV',
            field=models.CharField(default='Full HD 1080p', max_length=100, verbose_name='Стандарт HDTV'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='bluetooth',
            field=models.CharField(default='нет', max_length=100, verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='digital_tuner',
            field=models.CharField(default='DVB-S2 , DVB-C , DVB-T2', max_length=100, verbose_name='Цифровые тюнеры'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='headphone_output',
            field=models.CharField(default='есть', max_length=100, verbose_name='Выход для наушников'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='location_stand',
            field=models.CharField(default='по бокам', max_length=100, verbose_name='Раположение подставки'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='massa',
            field=models.CharField(default='2 кг', max_length=100, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='number_HDMI_port',
            field=models.CharField(default='1', max_length=100, verbose_name='Кол-во HDMI портов'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='number_USB_port',
            field=models.CharField(default='1', max_length=100, verbose_name='Кол-во USB портов'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='power_sound',
            field=models.CharField(default='6 Вт', max_length=100, verbose_name='Мощность звука'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='screen_diagonal',
            field=models.CharField(default='22"', max_length=100, verbose_name='Диагональ экрана'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='screen_format',
            field=models.CharField(default='16:9', max_length=100, verbose_name='Формат экрана'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='screen_refresh',
            field=models.CharField(default='60 Гц', max_length=100, verbose_name='Частота обновления экрана'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='screen_resolution',
            field=models.CharField(default='FullHD, 1920x1080', max_length=100, verbose_name='Разрешение экрана'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='security',
            field=models.CharField(default='12 мес.', max_length=10, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='subwoofer',
            field=models.CharField(default='нет', max_length=100, verbose_name='Сабвуфер'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='teletext',
            field=models.CharField(default='есть', max_length=100, verbose_name='Телетекст'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='type_TV',
            field=models.CharField(default='телевизор LED', max_length=100, verbose_name='Тип телевизора'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='viewing_angle',
            field=models.CharField(default='178° / 178°', max_length=100, verbose_name='Угол обзора'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='wall_mounting',
            field=models.CharField(default='есть', max_length=100, verbose_name='Возможность крепления на стену'),
        ),
    ]
