# Generated by Django 3.1.2 on 2020-12-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0099_auto_20201203_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='volume_LTE',
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='add_color',
            field=models.CharField(default='чёрный', max_length=100, verbose_name='Дополнительный цвет'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='depth',
            field=models.CharField(default='125 мм', max_length=100, verbose_name='Толщина'),
        ),
    ]
