# Generated by Django 3.1.2 on 2020-12-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0100_auto_20201203_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartwatch',
            name='depth',
            field=models.CharField(default='125 мм', max_length=100, verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='RAM',
            field=models.CharField(default='1 ГБ', max_length=100, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='SIM_cart',
            field=models.CharField(default='есть', max_length=100, verbose_name='Слот для карты памяти'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='WIFI',
            field=models.CharField(default='есть', max_length=100, verbose_name='Поддержка Wi-Fi'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='battery_capacity',
            field=models.CharField(default='4100 мА*ч', max_length=100, verbose_name='Ёмкость аккумулятора'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='bluetooth',
            field=models.CharField(default='4.0', max_length=100, verbose_name='Версия Bluetooth'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='body_material',
            field=models.CharField(default='металл', max_length=100, verbose_name='Материал корпуса'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='cellular_communication',
            field=models.CharField(default='3G', max_length=100, verbose_name='Модуль сотовой связи'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='color',
            field=models.CharField(default='белый', max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='depth',
            field=models.CharField(default='8.6 мм', max_length=100, verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='flash',
            field=models.CharField(default='нет', max_length=100, verbose_name='Вспышка'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='front_camera',
            field=models.CharField(default='нет', max_length=100, verbose_name='Фронтальная камера'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='height',
            field=models.CharField(default='187.6 мм', max_length=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='internal_memory',
            field=models.CharField(default='8 ГБ', max_length=100, verbose_name='Встроенная память'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='massa',
            field=models.CharField(default='250 г', max_length=100, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='number_cores',
            field=models.CharField(default='4', max_length=100, verbose_name='Кол-во ядер'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='rear_camera',
            field=models.CharField(default='нет', max_length=100, verbose_name='Тыловая камера'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='screen_diagonal',
            field=models.CharField(default='7"', max_length=100, verbose_name='Диагональ экрана'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='screen_protection',
            field=models.CharField(default='нет', max_length=100, verbose_name='Защитное покрытие экрана'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='screen_resolutin',
            field=models.CharField(default='1024x600', max_length=100, verbose_name='Разрешение экрана'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='screen_technology',
            field=models.CharField(default='IPS', max_length=100, verbose_name='Технология изготовления экрана'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='time_job',
            field=models.CharField(default='14 ч', max_length=100, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='type_SIM',
            field=models.CharField(default='micro SDHC, micro SDXC, micro SD', max_length=100, verbose_name='Тип карты памяти'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='width',
            field=models.CharField(default='103.7 мм', max_length=100, verbose_name='Ширина'),
        ),
    ]
