# Generated by Django 3.1.2 on 2020-12-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0101_auto_20201203_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='RAM',
            field=models.CharField(default='128 МБ', max_length=100, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='SIM_cart',
            field=models.CharField(default='есть', max_length=100, verbose_name='Слот для карты памяти'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='WIFI',
            field=models.CharField(default='нет', max_length=100, verbose_name='Поддержка Wi-Fi'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='audio_jack',
            field=models.CharField(default='нет', max_length=100, verbose_name='Аудиоразъёмы'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='battery_capacity',
            field=models.CharField(default='1800 мА*ч', max_length=100, verbose_name='Ёмкость аккумулятора'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='bluetooth',
            field=models.CharField(default='нет', max_length=100, verbose_name='Поддержка Bluetooth'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='depth',
            field=models.CharField(default='9.4 мм', max_length=100, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='display_diagonal',
            field=models.CharField(default='6"', max_length=100, verbose_name='Диагональ дисплея'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='display_resolution',
            field=models.CharField(default='800x600', max_length=100, verbose_name='Разрешение дисплея'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='display_sensor',
            field=models.CharField(default='нет', max_length=100, verbose_name='Сенсорный дисплей'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='graphic',
            field=models.CharField(default='PNG, GIF, BMP, JPG', max_length=100, verbose_name='графические'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='height',
            field=models.CharField(default='163.6 мм', max_length=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='internal_memory',
            field=models.CharField(default='4 ГБ', max_length=100, verbose_name='Встроенная память'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='massa',
            field=models.CharField(default='148 г', max_length=100, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='modile_communication',
            field=models.CharField(default='нет', max_length=100, verbose_name='Мобильная связь'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='screen_color',
            field=models.CharField(default='нет', max_length=100, verbose_name='Цветной экран'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='security',
            field=models.CharField(default='12 мес.', max_length=10, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='sound',
            field=models.CharField(default='нет', max_length=100, verbose_name='звуковые'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='text',
            field=models.CharField(default='MOBI, PDF, EPub, FB2, RTF, TXT, PDB', max_length=100, verbose_name='текстовые'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='time_job',
            field=models.CharField(default='14 ч', max_length=100, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='video',
            field=models.CharField(default='нет', max_length=100, verbose_name='видео'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='width',
            field=models.CharField(default='116 мм', max_length=100, verbose_name='Ширина'),
        ),
    ]
