# Generated by Django 3.1.2 on 2020-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0102_auto_20201203_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='massa',
        ),
        migrations.AlterField(
            model_name='column',
            name='analog_connector',
            field=models.CharField(default='нет', max_length=100, verbose_name='Аналоговые разъёмы'),
        ),
        migrations.AlterField(
            model_name='column',
            name='bluetooth',
            field=models.CharField(default='4.2', max_length=100, verbose_name='Версия Bluetooth'),
        ),
        migrations.AlterField(
            model_name='column',
            name='depth',
            field=models.CharField(default='176 мм', max_length=100, verbose_name='Глубина фронтальных колонок'),
        ),
        migrations.AlterField(
            model_name='column',
            name='height',
            field=models.CharField(default='210 мм', max_length=100, verbose_name='Высота фронтальных колонок'),
        ),
        migrations.AlterField(
            model_name='column',
            name='interface_USB',
            field=models.CharField(default='нет', max_length=100, verbose_name='Интерфейс USB Type A(для флешки)'),
        ),
        migrations.AlterField(
            model_name='column',
            name='material_front_column',
            field=models.CharField(default='пластик', max_length=100, verbose_name='Материал корпуса фронтальных колонок'),
        ),
        migrations.AlterField(
            model_name='column',
            name='max_playback_frequency',
            field=models.CharField(default='20000 Гц', max_length=100, verbose_name='Мах частота воспроизведения (Гц)'),
        ),
        migrations.AlterField(
            model_name='column',
            name='min_playback_frequency',
            field=models.CharField(default='60 Гц', max_length=100, verbose_name='Мин частота воспроизведения (Гц)'),
        ),
        migrations.AlterField(
            model_name='column',
            name='power',
            field=models.CharField(default='20 Вт', max_length=100, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='column',
            name='power_front_column',
            field=models.CharField(default='2x10 Вт', max_length=100, verbose_name='Мощность фронтальных колонок'),
        ),
        migrations.AlterField(
            model_name='column',
            name='signal_noise',
            field=models.CharField(default='80 дБ', max_length=100, verbose_name='Соотношение сигнал/шум'),
        ),
        migrations.AlterField(
            model_name='column',
            name='type_wired_connection',
            field=models.CharField(default='3.5 Jack', max_length=100, verbose_name='Тип проводного соединения'),
        ),
        migrations.AlterField(
            model_name='column',
            name='width',
            field=models.CharField(default='89 мм', max_length=100, verbose_name='Ширина фронтальных колонок'),
        ),
        migrations.AlterField(
            model_name='column',
            name='wireless_connection',
            field=models.CharField(default='Bluetooth', max_length=100, verbose_name='Беспроводное подключение'),
        ),
    ]
