# Generated by Django 3.1.2 on 2020-12-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0104_auto_20201203_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Headphone',
            new_name='Headphones',
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='category',
            field=models.CharField(default='brackettv', max_length=250, verbose_name='имя модели'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='PCI_Express',
            field=models.CharField(default='3.0', max_length=100, verbose_name='Версия PCI Express'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='main_power_connector',
            field=models.CharField(default='24-pin', max_length=100, verbose_name='Основной разъём питания'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='processor_power_connector',
            field=models.CharField(default='4-pin', max_length=100, verbose_name='Разъём питания процессора'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='slot_PCI',
            field=models.CharField(default='нет', max_length=100, verbose_name='Кол-во слотов PCI'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='slot_memory',
            field=models.CharField(default='2', max_length=100, verbose_name='Кол-во слотов памяти'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='speed_network_adapter',
            field=models.CharField(default='1000 Мбит/с', max_length=100, verbose_name='Скорость сетевого адаптера'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='type_memory',
            field=models.CharField(default='DDR3', max_length=100, verbose_name='Тип поддерживаемой памяти'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='volume_memory',
            field=models.CharField(default='32 ГБ', max_length=100, verbose_name='Мак объём памяти'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='TDP',
            field=models.CharField(default='25 Вт', max_length=100, verbose_name='Тепловыделение(TDP)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='frequency_processor',
            field=models.CharField(default='1450 МГц', max_length=100, verbose_name='Базовая частота процессора (МГц)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='max_frequency_RAM',
            field=models.CharField(default='1333 МГц', max_length=100, verbose_name='Мак частота оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='max_temperature',
            field=models.CharField(default='90 °C', max_length=100, verbose_name='Мак температура процессора'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='max_thread',
            field=models.CharField(default='2 шт', max_length=100, verbose_name='Мак число потоков'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='max_volume_memory',
            field=models.CharField(default='32 ГБ', max_length=100, verbose_name='Мак поддерживаемый объём памяти'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='min_frequency_RAM',
            field=models.CharField(default='1333 МГц', max_length=100, verbose_name='Мин частота оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='number_core',
            field=models.CharField(default='2', max_length=100, verbose_name='Кол-во ядер'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='type_memory',
            field=models.CharField(default='DDR3', max_length=100, verbose_name='Тип памяти'),
        ),
        migrations.AlterField(
            model_name='rammemory',
            name='bandwidth',
            field=models.CharField(default='PC6400', max_length=100, verbose_name='Пропускная способность'),
        ),
        migrations.AlterField(
            model_name='rammemory',
            name='frequency',
            field=models.CharField(default='800 МГц', max_length=100, verbose_name='Тактовая частота'),
        ),
        migrations.AlterField(
            model_name='rammemory',
            name='number_module',
            field=models.CharField(default='1 шт', max_length=100, verbose_name='Кол-во модулей в комплекте'),
        ),
        migrations.AlterField(
            model_name='rammemory',
            name='total_sum_memory',
            field=models.CharField(default='2 ГБ', max_length=100, verbose_name='Объем одного модуля памяти '),
        ),
        migrations.AlterField(
            model_name='rammemory',
            name='type_memory',
            field=models.CharField(default='DDR2', max_length=100, verbose_name='Тип памяти'),
        ),
        migrations.AlterField(
            model_name='server',
            name='base_frequency',
            field=models.CharField(default='3500 МГц', max_length=100, verbose_name='Базовая частота'),
        ),
        migrations.AlterField(
            model_name='server',
            name='depth',
            field=models.CharField(default='335 мм', max_length=100, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='server',
            name='frequency_RAM',
            field=models.CharField(default='3500 МГц', max_length=100, verbose_name='Частота оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='server',
            name='height',
            field=models.CharField(default='359 мм', max_length=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='server',
            name='massa',
            field=models.CharField(default='5 кг', max_length=100, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='server',
            name='max_sum_RAM',
            field=models.CharField(default='64 ГБ', max_length=100, verbose_name='Мак возможный суммарный объём ОЗУ'),
        ),
        migrations.AlterField(
            model_name='server',
            name='processor_socket',
            field=models.CharField(default='LGA1151', max_length=100, verbose_name='Процессорные сокеты'),
        ),
        migrations.AlterField(
            model_name='server',
            name='storage_capacity',
            field=models.CharField(default='1 ТБ', max_length=100, verbose_name='Объём установленных накопителей'),
        ),
        migrations.AlterField(
            model_name='server',
            name='storage_interface',
            field=models.CharField(default='SATA', max_length=100, verbose_name='Интерфейс накопителей'),
        ),
        migrations.AlterField(
            model_name='server',
            name='type_installed_drives',
            field=models.CharField(default='HDD', max_length=100, verbose_name='Тип установленных накопителей'),
        ),
        migrations.AlterField(
            model_name='server',
            name='typr_RAM',
            field=models.CharField(default='DDR4 DIMM ECC', max_length=100, verbose_name='Тип оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='server',
            name='volume_RAM',
            field=models.CharField(default='8 ГБ', max_length=100, verbose_name='Объём установленной оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='server',
            name='width',
            field=models.CharField(default='175 мм', max_length=100, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='depth',
            field=models.CharField(default='350 мм', max_length=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='height',
            field=models.CharField(default='380 мм', max_length=100, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='width',
            field=models.CharField(default='175 мм', max_length=100, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='category',
            field=models.CharField(default='tv', max_length=250, verbose_name='имя модели'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='PCI_Express',
            field=models.CharField(default='2.0', max_length=100, verbose_name='Версия PCI Express'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='frequency_memory',
            field=models.CharField(default='5012 МГц', max_length=100, verbose_name='Эффективная частота памяти(МГц)'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='frequency_videochip',
            field=models.CharField(default='954 МГц', max_length=100, verbose_name='Штатная частота работы видеочипа(МГц)'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='height',
            field=models.CharField(default='140 мм', max_length=100, verbose_name='Длина видеокарты'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='interface_connection',
            field=models.CharField(default='PCI-E', max_length=100, verbose_name='Интерфейс подключения'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='max_power_consumption',
            field=models.CharField(default='19 Вт', max_length=100, verbose_name='Мак энергопотребление'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='power_supply',
            field=models.CharField(default='300 Вт', max_length=100, verbose_name='Рекомендуемый блок питания'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='ray_tracing',
            field=models.CharField(default='нет', max_length=100, verbose_name='Поддержка трассировки лучей'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='temperature_processor',
            field=models.CharField(default='95°', max_length=100, verbose_name='Мах температура процессора'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='type_memory',
            field=models.CharField(default='GDDR5', max_length=100, verbose_name='Тип памяти'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='videochip',
            field=models.CharField(default='1', max_length=100, verbose_name='Кол-во видеочипов'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='volume_video_memory',
            field=models.CharField(default='1 ГБ', max_length=100, verbose_name='Объём видеопамяти'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='width',
            field=models.CharField(default='3.5 мм', max_length=100, verbose_name='Толщина видеокарты'),
        ),
    ]
