# Generated by Django 3.1.2 on 2020-12-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0105_auto_20201204_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stove',
            old_name='manufacture',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='headphones',
            name='category',
            field=models.CharField(default='headphones', max_length=250, verbose_name='имя модели'),
        ),
    ]
