# Generated by Django 3.1.2 on 2020-12-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0106_auto_20201204_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drymachine',
            old_name='valume',
            new_name='volume',
        ),
    ]
