# Generated by Django 3.1.2 on 2020-12-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0110_auto_20201204_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washmachine',
            name='depth',
            field=models.CharField(default='29 см', max_length=10, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='height',
            field=models.CharField(default='29 см', max_length=10, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='massa',
            field=models.CharField(default='29 кг', max_length=10, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='width',
            field=models.CharField(default='29 см', max_length=10, verbose_name='Ширина'),
        ),
    ]
