# Generated by Django 3.1.2 on 2020-12-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0111_auto_20201204_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washmachine',
            name='Number_programs',
        ),
        migrations.AddField(
            model_name='washmachine',
            name='number_programs',
            field=models.CharField(default='2', max_length=10, verbose_name='Кол-во программ стирки'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='drive',
            field=models.CharField(default='нет', max_length=10, verbose_name='Прямой привод'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='enegry',
            field=models.CharField(default='1 Вт', max_length=10, verbose_name='Потребляемая энергия'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='load',
            field=models.CharField(default='1 кг', max_length=10, verbose_name='Загрузка белья для стирки и отжима'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='max_press',
            field=models.CharField(default='5', max_length=10, verbose_name='Мах скорость отжима'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='max_time_postponement',
            field=models.CharField(default='5 ч', max_length=10, verbose_name='Мах вр отсрочки запуска'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='motor',
            field=models.CharField(default='есть', max_length=10, verbose_name='Инверторный двигатель'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='postponing_start',
            field=models.CharField(default='есть', max_length=10, verbose_name='Отсрочка запуска'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='steam',
            field=models.CharField(default='есть', max_length=10, verbose_name='Обработка паром'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='upload_type',
            field=models.CharField(default='фронтальная', max_length=10, verbose_name='Тип загрузки'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='voice',
            field=models.CharField(default='есть', max_length=10, verbose_name='Звуковой сигнал окончания стирки'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='voltage',
            field=models.CharField(default='есть', max_length=10, verbose_name='Защита от скачков напряжения'),
        ),
    ]
