# Generated by Django 3.1.2 on 2020-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0112_auto_20201204_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='washmachine',
            old_name='No_child',
            new_name='no_child',
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='enegry',
            field=models.CharField(default='0.7 Вт', max_length=10, verbose_name='Потребляемая энергия за цикл'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='max_press',
            field=models.CharField(default='800 об/мин', max_length=10, verbose_name='Мах скорость отжима'),
        ),
        migrations.AlterField(
            model_name='washmachine',
            name='upload_type',
            field=models.CharField(default='фронтальная', max_length=20, verbose_name='Тип загрузки'),
        ),
    ]
