# Generated by Django 3.1.2 on 2020-12-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0114_auto_20201204_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='manufacture',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='smartwatch',
            old_name='manufacture',
            new_name='country',
        ),
    ]
