# Generated by Django 3.1.2 on 2020-12-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0115_auto_20201204_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='add_color',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='color',
        ),
    ]
