# Generated by Django 3.1.2 on 2020-12-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0116_auto_20201204_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='manufacture',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='tablet',
            old_name='manufacture',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='color',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='max_memory_card_size',
        ),
        migrations.RemoveField(
            model_name='smartwatch',
            name='body_color',
        ),
        migrations.RemoveField(
            model_name='smartwatch',
            name='strap_color',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='color',
        ),
    ]
