# Generated by Django 3.1.2 on 2020-12-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0119_auto_20201204_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablet',
            old_name='screen_resolutin',
            new_name='screen_resolution',
        ),
        migrations.RemoveField(
            model_name='brackettv',
            name='color',
        ),
        migrations.AlterField(
            model_name='tv',
            name='depth',
            field=models.CharField(default='50 см', max_length=100, verbose_name='Толщина'),
        ),
    ]
