# Generated by Django 3.1.2 on 2020-12-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0120_auto_20201204_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='manufacture',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='headphones',
            old_name='manufacture',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='column',
            name='color',
        ),
    ]
