# Generated by Django 3.1.2 on 2020-12-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0121_auto_20201204_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemunit',
            old_name='manufacture',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='headphones',
            name='color',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='color',
        ),
    ]
