# Generated by Django 3.1.2 on 2020-12-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0123_auto_20201204_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='typr_RAM',
            new_name='type_RAM',
        ),
    ]
