# Generated by Django 3.1.2 on 2020-12-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0125_auto_20201205_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stove',
            name='color',
        ),
    ]
