# Generated by Django 3.1.2 on 2020-12-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0126_remove_stove_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stove',
            name='depth',
            field=models.CharField(default='60 см', max_length=100, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='stove',
            name='grill',
            field=models.CharField(default='есть', max_length=100, verbose_name='Гриль'),
        ),
        migrations.AlterField(
            model_name='stove',
            name='height',
            field=models.CharField(default='85 см', max_length=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='stove',
            name='max_power_consumption',
            field=models.CharField(default='3 кВт', max_length=10, verbose_name='Мак потребляемая мощность'),
        ),
        migrations.AlterField(
            model_name='stove',
            name='max_temperature',
            field=models.CharField(default='250°', max_length=100, verbose_name='Мах температура'),
        ),
        migrations.AlterField(
            model_name='stove',
            name='security',
            field=models.CharField(default='12 мес.', max_length=10, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='stove',
            name='supply_voltage',
            field=models.CharField(default='220/230 В', max_length=100, verbose_name='Напряжение питания'),
        ),
        migrations.AlterField(
            model_name='stove',
            name='timer',
            field=models.CharField(default='есть', max_length=100, verbose_name='Таймер'),
        ),
    ]
