# Generated by Django 3.1.2 on 2020-12-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0127_auto_20201206_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microwaveoven',
            name='color',
        ),
        migrations.AlterField(
            model_name='microwaveoven',
            name='security',
            field=models.CharField(default='24 мес.', max_length=10, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='microwaveoven',
            name='timer',
            field=models.CharField(default='90 мин', max_length=100, verbose_name='Таймер'),
        ),
    ]
