# Generated by Django 3.1.2 on 2020-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0128_auto_20201206_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kettle',
            name='color',
        ),
        migrations.AlterField(
            model_name='microwaveoven',
            name='country',
            field=models.CharField(default='Китай', max_length=200, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='microwaveoven',
            name='programs',
            field=models.CharField(default='есть', max_length=100, verbose_name='Автоматические программы приготовления'),
        ),
        migrations.AlterField(
            model_name='microwaveoven',
            name='security',
            field=models.CharField(default='12 мес.', max_length=10, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='microwaveoven',
            name='start',
            field=models.CharField(default='есть', max_length=100, verbose_name='Отсрочка старта'),
        ),
    ]
