# Generated by Django 3.1.2 on 2020-12-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0130_auto_20201206_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drymachine',
            name='color',
        ),
        migrations.RemoveField(
            model_name='hairclipper',
            name='add_color',
        ),
        migrations.RemoveField(
            model_name='hairclipper',
            name='color',
        ),
        migrations.RemoveField(
            model_name='hairdryer',
            name='add_color',
        ),
        migrations.RemoveField(
            model_name='hairdryer',
            name='color',
        ),
        migrations.RemoveField(
            model_name='iron',
            name='color',
        ),
        migrations.RemoveField(
            model_name='iron',
            name='manufacture',
        ),
    ]
