# Generated by Django 3.1.2 on 2020-12-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0131_auto_20201207_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washmachine',
            name='color',
        ),
        migrations.RemoveField(
            model_name='washmachine',
            name='manufacture',
        ),
    ]
