# Generated by Django 3.1.2 on 2020-12-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0134_auto_20201207_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairclipper',
            name='max_power_consumption',
        ),
        migrations.AlterField(
            model_name='hairclipper',
            name='charging_time',
            field=models.CharField(default='8 ч', max_length=100, verbose_name='Время зарядки'),
        ),
        migrations.AlterField(
            model_name='hairclipper',
            name='country',
            field=models.CharField(default='Китай', max_length=200, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='hairclipper',
            name='food',
            field=models.CharField(default='от сети/аккумулятора', max_length=100, verbose_name='Питание'),
        ),
        migrations.AlterField(
            model_name='hairclipper',
            name='massa',
            field=models.CharField(default='463 г', max_length=100, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='hairdryer',
            name='country',
            field=models.CharField(default='Китай', max_length=200, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='hairdryer',
            name='massa',
            field=models.CharField(default='600 г', max_length=100, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='hairdryer',
            name='security',
            field=models.CharField(default='24 мес.', max_length=10, verbose_name='Гарантия'),
        ),
    ]
