# Generated by Django 3.1.2 on 2020-12-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0135_auto_20201208_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemunit',
            name='country',
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='adjustment',
            field=models.CharField(default='наклон и поворот', max_length=100, verbose_name='Способ регулировки'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='angle_rotation',
            field=models.CharField(default='6°', max_length=100, verbose_name='Угол поворота ответной части'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='tilt_angle_down',
            field=models.CharField(default='6°', max_length=100, verbose_name='Угол наклона вниз'),
        ),
        migrations.AlterField(
            model_name='brackettv',
            name='tilt_angle_up',
            field=models.CharField(default='6°', max_length=100, verbose_name='Угол наклона вверх'),
        ),
        migrations.AlterField(
            model_name='column',
            name='country',
            field=models.CharField(default='Китай', max_length=200, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='USB',
            field=models.CharField(default='micro USB', max_length=100, verbose_name='Тип USB разъёма'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='country',
            field=models.CharField(default='Китай', max_length=200, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='type_SIM',
            field=models.CharField(default='micro SDHC , micro SD', max_length=100, verbose_name='Тип карты памяти'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='design_type',
            field=models.CharField(default='накладные', max_length=100, verbose_name='Тип конструкции'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='gaming_headphone',
            field=models.CharField(default='нет', max_length=100, verbose_name='Игровые наушники'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='microphone',
            field=models.CharField(default='нет', max_length=100, verbose_name='Микрофон'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='shape_cable_plug',
            field=models.CharField(default='L-образная', max_length=100, verbose_name='Форма штекера кабеля'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='signal_transmission',
            field=models.CharField(default='проводной', max_length=100, verbose_name='Способ передачи сигнала'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='type',
            field=models.CharField(default='проводные наушники', max_length=150, verbose_name='Тип изделия'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='depth',
            field=models.CharField(default='36 мм', max_length=100, verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='manufacture_chip',
            field=models.CharField(default='nVidia', max_length=100, verbose_name='Производитель видеочипа'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='manufacture_processor',
            field=models.CharField(default='Intel', max_length=100, verbose_name='Производитель процессора'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='screen_type',
            field=models.CharField(default='IPS', max_length=100, verbose_name='Тип экрана'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='country',
            field=models.CharField(default='Китай', max_length=200, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='depth',
            field=models.CharField(default='7.7 мм', max_length=100, verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='screen_technology',
            field=models.CharField(default='IPS', max_length=100, verbose_name='Технология изготовления экрана'),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='size_RAM',
            field=models.CharField(default='8 ГБ', max_length=100, verbose_name='Размер оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='type',
            field=models.CharField(default='ПК', max_length=150, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='type_RAM',
            field=models.CharField(default='DDR4', max_length=100, verbose_name='Тип оперативноё памяти'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='RAM',
            field=models.CharField(default='2 ГБ', max_length=100, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='country',
            field=models.CharField(default='Китай', max_length=200, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='front_camera',
            field=models.CharField(default='есть', max_length=100, verbose_name='Фронтальная камера'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='internal_memory',
            field=models.CharField(default='32 ГБ', max_length=100, verbose_name='Встроенная память'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='rear_camera',
            field=models.CharField(default='есть', max_length=100, verbose_name='Тыловая камера'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='type_SIM',
            field=models.CharField(default='micro SD', max_length=100, verbose_name='Тип карты памяти'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='depth',
            field=models.CharField(default='50 мм', max_length=100, verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='height',
            field=models.CharField(default='50 мм', max_length=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='massa',
            field=models.CharField(default='53 кг', max_length=100, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='number_HDMI_port',
            field=models.CharField(default='4', max_length=100, verbose_name='Кол-во HDMI портов'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='number_USB_port',
            field=models.CharField(default='3', max_length=100, verbose_name='Кол-во USB портов'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='power_sound',
            field=models.CharField(default='60 Вт', max_length=100, verbose_name='Мощность звука'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='width',
            field=models.CharField(default='50 мм', max_length=100, verbose_name='Ширина'),
        ),
    ]
