# Generated by Django 3.1.2 on 2021-01-19 11:50

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0136_auto_20201211_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Имя')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.mainm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='country',
            field=models.CharField(default='Китай', max_length=200, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='security',
            field=models.CharField(default='36 мес.', max_length=10, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='type_memory',
            field=models.CharField(default='DDR4', max_length=100, verbose_name='Тип поддерживаемой памяти'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='frequency_processor',
            field=models.CharField(default='3700 МГц', max_length=100, verbose_name='Базовая частота процессора (МГц)'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='security',
            field=models.CharField(default='36 мес.', max_length=10, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='type_memory',
            field=models.CharField(default='DDR4', max_length=100, verbose_name='Тип памяти'),
        ),
        migrations.AlterField(
            model_name='server',
            name='manufacture_processor',
            field=models.CharField(default='Intel', max_length=100, verbose_name='Производитель процессоров'),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='core_processor',
            field=models.CharField(default='4', max_length=100, verbose_name='Кол-во ядер процессора'),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='form_factor',
            field=models.CharField(default='Mini-Tower', max_length=100, verbose_name='Форм-фактор корпуса'),
        ),
        migrations.AlterField(
            model_name='systemunit',
            name='frequency_processor',
            field=models.CharField(default='3600 МГц', max_length=100, verbose_name='Частота процессора'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='PCI_Express',
            field=models.CharField(default='3.0', max_length=100, verbose_name='Версия PCI Express'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='country',
            field=models.CharField(default='Китай', max_length=200, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='security',
            field=models.CharField(default='36 мес.', max_length=10, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='width',
            field=models.CharField(default='35 мм', max_length=100, verbose_name='Толщина видеокарты'),
        ),
    ]
